Add optional headers to DavResource:mkCol()
bitfireAT/dav4jvm pull request #46
Opened 2024-06-03 11:09 UTC by ZetaTom

Allow custom headers to be set in `DavResource:mkCol()`.

2024-06-03 11:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitfireAT/dav4jvm?pullRequest=46) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitfireAT/dav4jvm?pullRequest=46) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitfireAT/dav4jvm?pullRequest=46) it.</sub>

2024-06-04 16:20 UTC, ArnyminerZ requested changes

2024-06-04 16:20 UTC, ArnyminerZ commented on src/main/kotlin/at/bitfire/dav4jvm/DavResource.kt
> +                .method(method, rqBody)
Please, use only 4 spaces instead of 8.

2024-06-05 09:47 UTC, rfc2822 commented
@ZetaTom Thanks for your PR! Can you please sign the CLA so that we are allowed to merge and use it?

2024-06-10 08:54 UTC, ZetaTom commented
@rfc2822 Apologies, I've signed the CLA since.

2024-06-10 08:55 UTC, merged